[package]
name = "tfn-test-staking-meta"
version = "0.0.1"
edition = "2018"
publish = false
authors = [ "DrDelphi",]

[dev-dependencies]

[dependencies.tfn-test-staking]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.4"
